# Generated by Django 3.2.8 on 2023-11-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prestacionSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('entidad', models.CharField(max_length=100)),
                ('periodicidad', models.CharField(max_length=50)),
                ('beneficios', models.TextField()),
                ('requisitos', models.TextField()),
                ('sitio_oficial', models.URLField()),
            ],
        ),
    ]
