# Generated by Django 3.2.8 on 2023-11-17 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuenta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacanteLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tiempo', models.CharField(max_length=200)),
                ('ubicacion', models.CharField(max_length=200)),
                ('descripcion', models.TextField(max_length=500)),
                ('responsabilidades', models.TextField(max_length=500)),
                ('requisitos', models.TextField(max_length=500)),
                ('beneficios', models.TextField(max_length=500)),
                ('oferta', models.CharField(max_length=200)),
                ('disponibilidad', models.BooleanField(default=False)),
                ('empleador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuenta.empleador')),
            ],
        ),
    ]
