# Generated by Django 4.2.4 on 2023-11-05 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20231104_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacanteLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tiempo', models.CharField(max_length=200)),
                ('ubicacion', models.CharField(max_length=200)),
                ('descripcion', models.TextField(max_length=500)),
                ('responsabilidades', models.TextField(max_length=500)),
                ('requisitos', models.TextField(max_length=500)),
                ('beneficios', models.TextField(max_length=500)),
                ('oferta', models.CharField(max_length=200)),
                ('empleador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.empleador')),
            ],
        ),
    ]
