# Generated by Django 4.2.4 on 2023-11-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacantelaboral',
            name='disponibilidad',
            field=models.BooleanField(default=False),
        ),
    ]
