# Generated by Django 3.2.8 on 2023-11-09 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20231104_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='calificacion_promedio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
