# Generated by Django 3.2.8 on 2023-09-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=30)),
                ('correo_electronico', models.CharField(max_length=50)),
                ('celular', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('contraseña', models.CharField(max_length=20)),
                ('estado', models.BooleanField(default=True)),
                ('identificacion', models.IntegerField()),
                ('biografia', models.TextField()),
                ('certificaciones', models.TextField()),
                ('habilidades', models.TextField()),
                ('experiencia_laboral', models.TextField()),
                ('historial_contratacion', models.TextField()),
            ],
        ),
    ]
