# Generated by Django 3.2.8 on 2023-09-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='id',
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='certificaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='historial_contratacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='identificacion',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
