# Generated by Django 3.2.8 on 2023-11-17 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabajador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofertaservicio',
            name='contacto',
        ),
    ]
