# Generated by Django 3.2.8 on 2023-11-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajador', '0002_remove_ofertaservicio_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertaservicio',
            name='calificacion_promedio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
