# Generated by Django 4.2.4 on 2023-11-05 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20231104_0846'),
        ('trabajador', '0002_auto_20230924_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='ofertaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=200)),
                ('disponibilidad', models.CharField(max_length=200)),
                ('restricciones', models.TextField(max_length=500)),
                ('lugar', models.TextField(max_length=500)),
                ('contacto', models.TextField(max_length=50)),
                ('precio', models.CharField(max_length=200)),
                ('sigue', models.BooleanField(default=False)),
                ('trabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.trabajador')),
            ],
        ),
    ]
