# Generated by Django 4.2.4 on 2023-11-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajador', '0003_ofertaservicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertaservicio',
            name='contacto',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ofertaservicio',
            name='lugar',
            field=models.TextField(max_length=80),
        ),
        migrations.AlterField(
            model_name='ofertaservicio',
            name='precio',
            field=models.CharField(max_length=30),
        ),
    ]
