# Generated by Django 3.2.8 on 2023-11-17 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='calificacion_promedio',
        ),
    ]
