# Generated by Django 3.2.8 on 2023-11-21 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0002_remove_trabajador_calificacion_promedio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleador',
            name='foto',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='foto',
            field=models.ImageField(default='NULL', upload_to='images/'),
            preserve_default=False,
        ),
    ]
