# Generated by Django 3.2.8 on 2023-11-17 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuenta', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calidad_servicio', models.PositiveIntegerField()),
                ('puntualidad', models.PositiveIntegerField()),
                ('profesionalismo', models.PositiveIntegerField()),
                ('cumplimiento_acuerdos', models.PositiveIntegerField()),
                ('trato_personal', models.PositiveIntegerField()),
                ('eficiencia', models.PositiveIntegerField()),
                ('empleador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuenta.empleador')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuenta.trabajador')),
            ],
        ),
    ]
